config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "pages#home"		 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
 		
   resources :users, only: [:show] do
     member do
       post '/verify_phone_number' => 'users#verify_phone_number'
       patch '/update_phone_number' => 'users#update_phone_number'
     end
   end

   resources :venues do
    member do		
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
      resources :photos, only: [:create, :destroy]
      resources :reservations, only: [:create]
      resources :calendars
   end
  
   resources :guest_reviews, only: [:create, :destroy]
   resources :host_reviews, only: [:create, :destroy]
  		
   get '/previous_reservations' => 'reservations#previous_reservations'
   get '/current_reservations' => 'reservations#current_reservations'

   get 'about' => 'pages#about'
   get 'search' => 'pages#search'
   get 'terms' => 'pages#terms'
   get 'faq' => 'pages#faq'
   get 'blog' => 'pages#blog'
   get 'careers' => 'pages#careers'
   get 'support' => 'pages#support'


 # ---- AirKong ------
   get 'dashboard' => 'dashboards#index'

   resources :reservations, only: [:approve, :decline] do
     member do
       post '/approve' => "reservations#approve"
       post '/decline' => "reservations#decline"
     end
   end

   resources :revenues, only: [:index]

   resources :conversations, only: [:index, :create, :update, :destroy]  do
     resources :messages, only: [:index, :create, :update, :destroy]
   end

   get '/host_calendar' => "calendars#host"
   get '/payment_method' => "users#payment"
   get '/payout_method' => "users#payout"
   post '/add_card' => "users#add_card"

   get '/notification_settings' => 'settings#edit'
   post '/notification_settings' => 'settings#update'
   delete '/notification_settings' => 'settings#destroy'

   get '/notifications' => 'notifications#index'

   mount ActionCable.server => '/cable'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  
  validates_presence_of :context, :conversation_id, :user_id
  after_create_commit :create_notification
  
  def message_time
    self.created_at.strftime("%D")
  end

  private

    def create_notification
      if self.conversation.sender_id == self.user_id
        sender = User.find(self.conversation.sender_id)
        Notification.create(content: "New message from #{sender.fullname}", user_id: self.conversation.recipient_id)
      else
        sender = User.find(self.conversation.recipient_id)
        Notification.create(content: "New message from #{sender.fullname}", user_id: self.conversation.sender_id)
      end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_conversation

  def index
    if current_user == @conversation.sender || current_user == @conversation.recipient
      @other = current_user == @conversation.sender ? @conversation.recipient : @conversation.sender
      @messages = @conversation.messages.order("created_at DESC")
    else
      redirect_to conversations_path, alert: "You don't have permission to view this."
    end
  end

  def create
    @message = @conversation.messages.new(message_params)
    @messages = @conversation.messages.order("created_at DESC")

    if @message.save
      ActionCable.server.broadcast "conversation_#{@conversation.id}", message: render_message(@message)
      redirect_to conversation_messages_path(@conversation)
    end
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      redirect_to @message, notice: 'Message was successfully updated.'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    # redirect_back(fallback_location: request.referer, notice: "Deleted...!")
    redirect_to conversation_messages_path, notice: "Deleted..."
  end
  
  private

    def render_message(message)
      self.render(partial: 'messages/message', locals: {message: message})
    end

    def set_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end

    def message_params
      params.require(:message).permit(:context, :user_id)
    end
end

app/views/messages/_message.html.erb
<section class="">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= image_tag message.user.image, class: "img-circle avatar-small" %>
            <%= message.user.fullname %>
            <span class="pull-right"><%= message.message_time %></span>
          </div>
    
          <div class="panel-body">
            <div class="container">
                
              <div class="col-md-11">
                <%= message.context %>
              </div>
              
              <div class="col-md-1">
                <%= link_to @conversation, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="far fa-trash-alt" aria-hidden="true"></i>
                <% end %>
              </div>
              
              <!--<div class="col-md-1">-->
              <!--  <= link_to @conversation do %>-->
      	       <!--   <i class="fa fa-pencil-alt"></i> -->
      	       <!-- < end %>-->
              <!--</div>      	       -->
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>  

app/views/messages/destroy.js.erb
$('#messages').html("<%= j render '_messages' %>")
<% if @conversation.messages.blank? %>
  $('#message_check').hide();
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'form' %>
<%= link_to 'Show', @message %> |
<%= link_to 'Back', conversation_path %>

app/views/messages/index.html.erb
<section class="">
  <div class="container">
    <div class="row">
      <div class="col-md-3 text-center">
        <%= image_tag @other.image, class: "img-circle avatar-medium" %>
        <strong><%= @other.fullname %></strong>
        <%= link_to "View Profile", @other, class: "btn btn-default" %>&nbsp;
      </div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
              Conversation with <%= @other.fullname %> 
            <input id="conversation_id" type="hidden" value="<%= @conversation.id %>">
          </div>
          <div class="panel-body">
            <div class="container text-center">
              <%= form_for [@conversation, @conversation.messages.new], remote: true do |f| %>
                <div class="form-group">
                  <%= f.text_field :context, placeholder: "Start a conversation", class: "form-control" %>
                </div>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <div>
                  <%= f.submit "Send Message", class: "btn btn-normal" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div id="chat">
          <%= render @messages %>
        </div>
      </div>
    </div>
  </div>
</section>  