config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "pages#home"		 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
 		
   resources :users, only: [:show] do
     member do
       post '/verify_phone_number' => 'users#verify_phone_number'
       patch '/update_phone_number' => 'users#update_phone_number'
     end
   end

   resources :venues do
    member do		
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
      resources :photos, only: [:create, :destroy]
      resources :reservations, only: [:create]
      resources :calendars
   end
  
   resources :guest_reviews, only: [:create, :destroy]
   resources :host_reviews, only: [:create, :destroy]
  		
   get '/previous_reservations' => 'reservations#previous_reservations'
   get '/current_reservations' => 'reservations#current_reservations'

   get 'about' => 'pages#about'
   get 'search' => 'pages#search'
   get 'terms' => 'pages#terms'
   get 'faq' => 'pages#faq'
   get 'blog' => 'pages#blog'
   get 'careers' => 'pages#careers'
   get 'support' => 'pages#support'


 # ---- AirKong ------
   get 'dashboard' => 'dashboards#index'

   resources :reservations, only: [:approve, :decline] do
     member do
       post '/approve' => "reservations#approve"
       post '/decline' => "reservations#decline"
     end
   end

   resources :revenues, only: [:index]

   resources :conversations, only: [:index, :create, :update, :destroy]  do
     resources :messages, only: [:index, :create, :update, :destroy]
   end

   get '/host_calendar' => "calendars#host"
   get '/payment_method' => "users#payment"
   get '/payout_method' => "users#payout"
   post '/add_card' => "users#add_card"

   get '/notification_settings' => 'settings#edit'
   post '/notification_settings' => 'settings#update'
   delete '/notification_settings' => 'settings#destroy'

   get '/notifications' => 'notifications#index'

   mount ActionCable.server => '/cable'
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row text-muted">
      <div class="col-lg-9 text-center text-lg-left my-auto">
        <ul class="list-inline mb-2">
          
          <li class="list-inline-item">
            <%= link_to "About", about_path, style: "text-decoration: none;" %>
          </li>
          
          <li class="list-inline-item">⋅</li>
          <li class="list-inline-item">
            <%= link_to "Support", support_path, style: "text-decoration: none;" %>
          </li>
          
          <li class="list-inline-item">⋅</li>
          <li class="list-inline-item">
            <%= link_to "Terms & Policy", terms_path, style: "text-decoration: none;" %>
          </li>
          
          <li class="list-inline-item">⋅</li>
          <li class="list-inline-item">
            <%= link_to "FAQ", faq_path, style: "text-decoration: none;" %>
          </li>

          <li class="list-inline-item">⋅</li>
          <li class="list-inline-item">
            <%= link_to "Blog", blog_path, style: "text-decoration: none;" %>
          </li>
          
          <li class="list-inline-item">⋅</li>
          <li class="list-inline-item">
            <%= link_to "Careers", careers_path, style: "text-decoration: none;" %>
					</li>
					
					<li class="list-inline-item">⋅</li>
          <li class="list-inline-item">
            <a herf="#" style="text-decoration: none;">ShindigSpace 2020. All Rights Reserved.</a>
					</li>
        </ul>
      </div>
      <div class="col-lg-3 h-100 text-center text-lg-left my-auto">
    		<ul class="list-inline mb-2">	
    			<li class="list-inline-item">
    				<a href="https://facebook.com" target="_blank">
  						<i class="fab fa-facebook fa-2x fa-fw"></i>
  					</a>
    			</li>
    
    			<li class="list-inline-item">
    				<a href="https://twitter.com" target="_blank">
  						<i class="fab fa-twitter-square fa-2x fa-fw"></i>
    				</a>
  				</li>
    
    			<li class="list-inline-item">
    				<a href="https://www.instagram.com/shindigspace/" target="_blank">
  						<i class="fab fa-instagram fa-2x fa-fw"></i>
  					</a>
    			</li>
    		</ul>	
			</div>
    </div>
  </div>
</footer>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <%  flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice','success') %>
       toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ShindigSpace", root_path, class: "navbar-brand" %>
      <!--< link_to image_tag("icon.svg", alt: "logo"), root_path, class: "navbar-brand" %>-->
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="navbar" class="navbar-collapse collapse">
     <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Event Spaces Near You", class: "form-control", id:"autoaddress" %>
          </div>
      <% end %>
      
      <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %>
          <li>
            <button class="btn btn-form btn-small">
              <%= link_to "List Event Space", new_user_registration_path, style: "color: white; text-decoration: none;" %>
            </button>
          </li>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li>
            <button class="btn btn-form btn-small">
              <%= link_to "List Event Space", new_venue_path, style: "color: white; text-decoration: none;" %>
            </button>
          </li>
          <li>
            <%= link_to notifications_path do %>
              <i class="fa fa-bell fa-2x icon-babu"></i>
              <span class="badge" id="navbar_num_of_unread"><%= current_user.unread if current_user.unread > 0 %></span>
            <% end %>
          </li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
              role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag current_user.image, class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "Manage Listing", venues_path %></li>
              <li><%= link_to "List Event Space", new_venue_path %></li>
              <li><%= link_to "Previous Reservations", previous_reservations_path %></li>
              <li><%= link_to "Current Reservations", current_reservations_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->  
</nav>

<% if (user_signed_in?) && !current_page?(root_path) %>
  <nav class="navbar navbar-default static-top" style="background-color: #ECF0F1;">
    <div class="container">
      <ul class="nav navbar-nav">
        <li <% if current_page?(current_user) %> class="active" <% end %> ><%= link_to "Profile", current_user %></li>
        <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "Dashboard", dashboard_path %></li>
        <li <% if current_page?(venues_path) %> class="active" <% end %> ><%= link_to "Manage Listings", venues_path %></li>
        <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "Messages", conversations_path %></li>
        <li <% if current_page?(revenues_path) %> class="active" <% end %> ><%= link_to "Revenues", revenues_path %></li>
        <li <% if current_page?(current_reservations_path) %> class="active" <% end %> ><%= link_to "Current Reservations", current_reservations_path %></li>
        <li <% if current_page?(host_calendar_path) %> class="active" <% end %> ><%= link_to "Host Calendar", host_calendar_path %></li>
        <li <% if current_page?(payment_method_path) %> class="active" <% end %> ><%= link_to "Account Settings", payment_method_path %></li>
      </ul>
    </div>
  </nav>
<% end %>